<aside class="w-64 bg-white flex flex-col p-6 border-r border-gray-200">
    <div class="flex items-center space-x-3 mb-10">
        <div class="p-2 bg-bri-blue rounded-lg"><svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0l3-3m0 0l3 3m-3-3v12"></path></svg></div>
        <span class="text-2xl font-bold text-bri-blue">DataBOX</span>
    </div>

    <div x-data="{ open: false }" class="relative"> @auth <button @click="open = !open" class="w-full flex items-center justify-center space-x-2 bg-bri-blue text-white font-semibold py-3 px-4 rounded-lg hover:bg-bri-blue-dark transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 ring-bri-blue"><span>Create New</span> <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg></button> <div x-show="open" @click.outside="open = false" x-cloak class="absolute z-10 mt-2 w-full bg-white rounded-md shadow-lg border"> <a href="#" @click.prevent="showUploadFileModal = true; open = false" class="block px-4 py-3 text-sm text-gray-700 hover:bg-gray-100"><div class="flex items-center space-x-2"><span>Upload File</span></div></a> <a href="#" @click.prevent="showCreateFolderModal = true; open = false" class="block px-4 py-3 text-sm text-gray-700 hover:bg-gray-100"><div class="flex items-center space-x-2"><span>New Folder</span></div></a></div> @else <a href="{{ route('login') }}" class="w-full flex items-center justify-center space-x-2 bg-bri-blue text-white font-semibold py-3 px-4 rounded-lg hover:bg-bri-blue-dark transition-colors"><span>Login to Create</span></a> @endauth</div>

    <nav class="mt-10 flex-1"><ul class="space-y-2"><li><a href="{{ route('dashboard') }}" class="flex items-center space-x-3 p-3 rounded-lg transition-colors {{ request()->routeIs('dashboard*') ? 'text-bri-blue font-semibold bg-blue-100' : 'text-gray-500 hover:text-gray-800 hover:bg-gray-100' }}"><span>Dashboard</span></a></li><li><a href="{{ route('recent') }}" class="flex items-center space-x-3 p-3 rounded-lg transition-colors {{ request()->routeIs('recent') ? 'text-bri-blue font-semibold bg-blue-100' : 'text-gray-500 hover:text-gray-800 hover:bg-gray-100' }}"><span>Recent</span></a></li><li><a href="{{ route('trash') }}" class="flex items-center space-x-3 p-3 rounded-lg transition-colors {{ request()->routeIs('trash') ? 'text-bri-blue font-semibold bg-blue-100' : 'text-gray-500 hover:text-gray-800 hover:bg-gray-100' }}"><span>Trash</span></a></li></ul></nav>
</aside>